version: "3.8"
services:
  bot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8080
  ngrok:
    image: "wernight/ngrok"
    ports:
      - "4040:4040"
    command: sh -c "if [ ! -z \"${NGROK_AUTH}\" ]; then ngrok authtoken ${NGROK_AUTH}; fi; ngrok http bot:8080"
