version: "3.8"
services:
  bot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app/public
    command: php -S 0.0.0.0:8080
  ngrok:
    image: "wernight/ngrok"
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_HOSTNAME: "${NGROK_HOSTNAME}"
      NGROK_PORT: "${NGROK_PORT}"

